<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-24T22:41:08 ICT" name="Default suite" finished-at="2022-09-24T22:41:09 ICT" duration-ms="62">
    <groups>
    </groups>
    <test started-at="2022-09-24T22:41:08 ICT" name="Default test" finished-at="2022-09-24T22:41:09 ICT" duration-ms="62">
      <class name="ujian.ujiankelima.testng.ParsingStringToNumericTest">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:ujian.ujiankelima.testng.ParsingStringToNumericTest@cb0755b]" started-at="2022-09-24T22:41:08 ICT" name="beforeTest" finished-at="2022-09-24T22:41:09 ICT" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:ujian.ujiankelima.testng.ParsingStringToNumericTest@cb0755b]" started-at="2022-09-24T22:41:09 ICT" name="beforeClass" finished-at="2022-09-24T22:41:09 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:ujian.ujiankelima.testng.ParsingStringToNumericTest@cb0755b]" started-at="2022-09-24T22:41:09 ICT" name="beforeMethod" finished-at="2022-09-24T22:41:09 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="testDevide()[pri:0, instance:ujian.ujiankelima.testng.ParsingStringToNumericTest@cb0755b]" started-at="2022-09-24T22:41:09 ICT" name="testDevide" finished-at="2022-09-24T22:41:09 ICT" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<346.6099853515625> but was:<346.61>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<346.6099853515625> but was:<346.61>
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:467)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:98)
at ujian.ujiankelima.testng.ParsingStringToNumericTest.testDevide(ParsingStringToNumericTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDevide -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:ujian.ujiankelima.testng.ParsingStringToNumericTest@cb0755b]" started-at="2022-09-24T22:41:09 ICT" name="afterMethod" finished-at="2022-09-24T22:41:09 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:ujian.ujiankelima.testng.ParsingStringToNumericTest@cb0755b]" started-at="2022-09-24T22:41:09 ICT" name="afterTest" finished-at="2022-09-24T22:41:09 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- ujian.ujiankelima.testng.ParsingStringToNumericTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
